from __future__ import annotations

from enum import StrEnum


class CaseState(StrEnum):
    DRAFT = "DRAFT"
    READY_TO_START = "READY_TO_START"
    CONTACTING_SUPPLIERS = "CONTACTING_SUPPLIERS"
    COLLECTING_OFFERS = "COLLECTING_OFFERS"
    NEGOTIATING = "NEGOTIATING"
    BUYER_REVIEW = "BUYER_REVIEW"
    LIMITED_COMPETITION = "LIMITED_COMPETITION"
    NO_VALID_OFFERS = "NO_VALID_OFFERS"
    WINNER_SELECTED = "WINNER_SELECTED"
    WINNER_NOTIFIED = "WINNER_NOTIFIED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"


class SupplierState(StrEnum):
    NOT_CONTACTED = "NOT_CONTACTED"
    REQUEST_SENT = "REQUEST_SENT"
    AWAITING_RESPONSE = "AWAITING_RESPONSE"
    WAITING_FOR_OFFER = "WAITING_FOR_OFFER"
    AWAITING_PRICE_CONFIRMATION = "AWAITING_PRICE_CONFIRMATION"
    NEEDS_CASE_ANSWER = "NEEDS_CASE_ANSWER"
    RFQ_REMINDER_SENT = "RFQ_REMINDER_SENT"
    RESPONDED_NEEDS_EXTRACTION = "RESPONDED_NEEDS_EXTRACTION"
    PRICE_EXTRACTED = "PRICE_EXTRACTED"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    CLARIFICATION_SENT = "CLARIFICATION_SENT"
    DISCOUNT_REQUEST_SENT = "DISCOUNT_REQUEST_SENT"
    FINAL_OFFER_RECEIVED = "FINAL_OFFER_RECEIVED"
    NO_RESPONSE = "NO_RESPONSE"
    REJECTED = "REJECTED"
    WINNER = "WINNER"
    CLOSED = "CLOSED"
    PAUSED_REVIEW = "PAUSED_REVIEW"
    ERROR = "ERROR"


TERMINAL_SUPPLIER_STATES = {
    SupplierState.FINAL_OFFER_RECEIVED,
    SupplierState.NO_RESPONSE,
    SupplierState.REJECTED,
    SupplierState.WINNER,
    SupplierState.CLOSED,
    SupplierState.PAUSED_REVIEW,
}